# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b7f08e82aded23092dbdcedc9ac4d1449146dbec81fc8d10c42b25a606ab5455d7058aa90a0c46b41dadab00b2efc6b19e335db73efdab4a29355c23aac9a03

test:
  secret_key_base: 0e81c23a7fce8d4e8ce2c763ed23edf64d19cb997616723bc26ca95c0a3dcdc806a1ecaf59e75233f4ec111aa290c4f22ef924febd27308667c920619c7e4a6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
